# Generated by Django 4.0.8 on 2022-11-15 08:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30, null=True)),
                ('goals', models.SmallIntegerField(null=True)),
                ('game_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=50, null=True)),
                ('country', models.CharField(max_length=20)),
                ('number', models.IntegerField()),
                ('positon', models.CharField(choices=[('GK', 'Goalkeeeper'), ('DF', 'Defender'), ('MD', 'Midfielder'), ('FW', 'Forward')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Lineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(choices=[('IN', 'IN start'), ('OUT', 'IN reserve')], max_length=3)),
                ('time_in', models.FloatField()),
                ('goals', models.SmallIntegerField(null=True)),
                ('card', models.CharField(choices=[('Y', 'Yellow'), ('Y2', 'Two yellow cards'), ('R', 'Straight red'), ('YR', 'Yellow + Straight red'), ('NUll', 'No cards')], max_length=4)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModelsDB.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModelsDB.player')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='participants',
            field=models.ManyToManyField(through='ModelsDB.Lineup', to='ModelsDB.player'),
        ),
    ]
