# Generated by Django 4.0.8 on 2022-11-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsDB', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='goals',
            new_name='g_conceded',
        ),
        migrations.AddField(
            model_name='game',
            name='g_scored',
            field=models.SmallIntegerField(null=True),
        ),
    ]
