# Generated by Django 4.0.8 on 2022-11-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsDB', '0002_rename_goals_game_g_conceded_game_g_scored'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='city',
            field=models.CharField(default=models.CharField(max_length=30), max_length=30, null=True),
        ),
    ]
