# Generated by Django 4.0.8 on 2022-10-26 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsDB', '0002_group_remove_person_shirt_size_alter_person_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='date_joined',
        ),
    ]
